# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-31 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=30)),
                ('description', models.TextField(blank=True, default=None, max_length=500)),
            ],
            options={
                'verbose_name': 'Smart Trashcan Name',
                'verbose_name_plural': 'Smart Trashcan Names',
            },
        ),
    ]
