# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-31 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoTrash_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, help_text='Enter name of room in the house, e.g. Kitchen', max_length=30)),
                ('description', models.TextField(blank=True, default=None, max_length=500)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.AlterModelOptions(
            name='trash',
            options={'ordering': ['-name'], 'verbose_name': 'Smart Trashcan Name', 'verbose_name_plural': 'Smart Trashcan Names'},
        ),
        migrations.AddField(
            model_name='trash',
            name='sensor_depth',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='trash',
            name='name',
            field=models.CharField(blank=True, default=None, help_text='Enter name of trash can', max_length=30),
        ),
    ]
