# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-31 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IoTrash_app', '0002_auto_20211031_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='trash',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='IoTrash_app.Room', verbose_name='Specify Room '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(default=None, help_text='Enter name of room in the house, e.g. Kitchen', max_length=30),
        ),
    ]
