# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-31 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoTrash_app', '0003_auto_20211031_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='trash',
            name='times_changed',
            field=models.IntegerField(default=0),
        ),
    ]
